Добавляет моковые данные
htmlacademy-ecmascript/1474119-big-trip-13 pull request #5
Opened 2020-12-02 02:28 UTC by YuShato

2020-12-05 14:53 UTC, olegsklyarov requested changes

2020-12-05 14:53 UTC, olegsklyarov commented on package.json
> +    "eslint-config-htmlacademy": "^0.6.0",
Указываем точную версию (без `^`).

2020-12-05 14:53 UTC, olegsklyarov commented on package.json
> +    "chart.js": "^2.9.4",
Все зависимости должны быть с точной версией (без `^`)

2020-12-05 14:53 UTC, olegsklyarov commented on src/utils/utils.js
> +const getRandomInt = (a = 0, b = 1) => {
1. Параметры должны быть говорящими, например `minValue` и `maxValue`
1. Пусть первый параметр всегда будет меньше или равен второму. Не к чему делать излишнюю гибкость, это путает и создает проблемы.
1. Значения по умолчанию — не очень хороший ход в данном случае. Пусть функция всегда принимает строго два параметра.

```
const getRandomInt = (minValue, maxValue) => Math.floor(minValue + Math.random() * (maxValue - minValue + 1));
```

2020-12-05 14:53 UTC, olegsklyarov commented on src/utils/utils.js
> +const randomBoolean = () => {
```
const getRandomBoolean = () => !!getRandomInt(0, 1);
```

2020-12-05 14:53 UTC, olegsklyarov commented on src/view/mock/data.js
> +  const offersCount = getRandomInt(specialOfferCount.MAX);
Создать в uilts отдельную функцию:
```
const getRandomPositiveInt = (maxValue) => getRandomInt(0, maxValue);
```

2020-12-05 14:53 UTC, olegsklyarov commented on src/view/mock/data.js
> +    return obj[keys[keys.length * Math.random() << 0]];
Создать в utils отдельную функцию `const getArrayRandomElement = (arr) => {...}` которая возвращает случайный элемент массива при помощи `getRandomPositiveNumber`

2020-12-05 14:53 UTC, olegsklyarov commented on src/view/mock/data.js
> +  const randomProperty = function (obj) {
Эту функцию нужно вынести в `utils.js`

2020-12-05 14:53 UTC, olegsklyarov commented on src/view/mock/data.js
> +  }, () => (arrayOfDescription[getRandomInt(arrayOfDescription.length - 1)]));
Использовать тут функцию `getArrayRandomElement`

2020-12-05 14:53 UTC, olegsklyarov commented on src/view/mock/data.js
> +  const isDate = Boolean(getRandomInt(0, 1));
Использовать функцию `getRandomBoolean`

2020-12-05 14:53 UTC, olegsklyarov commented on src/view/mock/data.js
> +    return dayjs(today);
Использовать тернарный оператор https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator

2020-12-05 14:53 UTC, olegsklyarov commented on src/view/mock/data.js
> +  return `${cities[getRandomInt(0, cities.length - 1)]}`;
Использовать функцию `getArrayRandomElement()` для получения случайного элемента из cities

2020-12-05 14:53 UTC, olegsklyarov commented on src/view/mock/data.js
> +  return `${events[getRandomInt(0, events.length - 1)]}`;
Использовать функцию `getArrayRandomElement()`

2020-12-05 14:53 UTC, olegsklyarov commented on src/view/mock/data.js
> +import {getRandomInt, randomBoolean} from "../../utils/utils.js";
Моки не должны быть во view. Выносим их в корень проекта.

2020-12-05 14:53 UTC, olegsklyarov commented on src/view/mock/data.js
> +  const mockTrip = {
Лишняя переменна mockTrip. Сразу return и объект

2020-12-05 14:53 UTC, olegsklyarov commented on src/view/tripPoint.js
> +  const timeGap = () => {
Выносим эту функцию в utils.

2020-12-06 02:44 UTC, YuShato commented on package.json
> +    "chart.js": "^2.9.4",
переустановила пакеты, исправила

2020-12-06 03:02 UTC, YuShato commented on src/utils/utils.js
> +const randomBoolean = () => {
исправила

2020-12-06 03:11 UTC, YuShato commented on src/view/mock/data.js
> +  const offersCount = getRandomInt(specialOfferCount.MAX);
исправила

2020-12-06 03:11 UTC, YuShato commented on src/utils/utils.js
> +const getRandomInt = (a = 0, b = 1) => {
есть вопрос, задам при созвоне

2020-12-06 03:12 UTC, YuShato commented on package.json
> +    "eslint-config-htmlacademy": "^0.6.0",
исправила

2020-12-06 03:14 UTC, YuShato commented on src/view/mock/data.js
> +import {getRandomInt, randomBoolean} from "../../utils/utils.js";
исправила

2020-12-06 03:21 UTC, YuShato commented on src/view/mock/data.js
> +  return `${events[getRandomInt(0, events.length - 1)]}`;
исправила

2020-12-06 03:23 UTC, YuShato commented on src/view/mock/data.js
> +  const mockTrip = {
исправила

2020-12-06 03:32 UTC, YuShato commented on src/view/tripPoint.js
> +  const timeGap = () => {
исправила

2020-12-06 03:32 UTC, YuShato commented on src/view/mock/data.js
> +  return `${cities[getRandomInt(0, cities.length - 1)]}`;
исправила

2020-12-16 16:44 UTC, olegsklyarov requested changes

2020-12-16 16:44 UTC, olegsklyarov commented on src/utils/form-template.js
> +  render(eventsFieldsetElement, generateTemplateElements(eventTypes, createEventTypeInput), TemplatePosition.BEFORE_END);
Такой подход, что цельный элемент DOM рендерится по кускам — не лучшая практика. Лучшим решение будет собрать весь элемент в строку из шаблонов и затем отрендерить его один раз в нужном месте DOM. Отправляю тебе в личку видео с демонстрацией как это можно сделать.

2020-12-16 16:44 UTC, olegsklyarov commented on src/utils/templates.js
> +import {createTripFilterForm} from "../view/filter-form.js";
Лучше сгруппировать шаблоны, относящиеся к одному элементу сайта в папки. Например вынести все шаблоны, относящиеся к форме добавления нового ивента.

2020-12-16 16:44 UTC, olegsklyarov commented on src/view/add-form.js
> +      <div class="event__field-group  event__field-group--destination">
Над этой строкой будет добавлен HTML с типами ивентов. Лучше его явно вставить тут как переменную. А значение передать как аргумент функции `creareAddForm()`. Это лучше, чем отрендерить этот HTML код, а потом через селекторы дорендеривать куски.

2020-12-16 16:44 UTC, olegsklyarov commented on src/view/add-form.js
> +        <input class="event__input  event__input--destination" id="event-destination-1" type="text" name="event-destination" value="Geneva" list="destination-list-1">
Под этим инпутом будет destinationList, его тоже лучше передать явно через аргумент и вставить тут `${destinationList}`

2020-12-16 16:44 UTC, olegsklyarov commented on src/view/add-form.js
> +    </header>
Тут так же нужны:
```
      ${eventTimeField}
      ${priceField}
      ${buttons}
```

2020-12-16 16:44 UTC, olegsklyarov commented on src/view/filter.js
> +      <input id="filter-${elem.name.toLocaleLowerCase()}" class="trip-filters__filter-input  visually-hidden" type="radio"    name="trip-filter" value="${elem.name.toLocaleLowerCase()}" ${elem.isChec
`elem.name.toLocaleLowerCase()` вынести в отдельную переменную и использовать в нескольких местах

2020-12-16 16:44 UTC, olegsklyarov commented on src/view/sorter-form.js
> +  return ` <h2 class="visually-hidden">Trip events</h2>
Везде по коду убрать лишние пробелы. Тут лишний пробел между кавычкой и тегом h2

2020-12-16 16:44 UTC, olegsklyarov commented on src/mock/data.js
> +const eventTimeLabels = [
Все константы выше, начиная с `filters`, — это не моки. Это вспомогательные массивы, они относятся к View, а не в контенту. Поэтому они не должны быть в папке `mock`.

2020-12-16 16:44 UTC, olegsklyarov commented on src/mock/data.js
> +const eventMockData = new Array(OFFERS_COUNT).fill().map(generateMockTripEvent);
У функции `fill()` должен быть указан аргумент (здесь и далее)

2020-12-16 16:44 UTC, olegsklyarov commented on src/mock/filter.js
> +import {eventMockData, today} from "./data.js";
Не нужно отдельно объявлять today. Если нужно текущее время, то просто пишем `dayjs()` без аргументов.

2020-12-16 16:44 UTC, olegsklyarov commented on src/mock/filter.js
> +const sortEventsByDate = () => {
Функция возвращает первое и последнее событие. Она не сортирует. Поэтому название нужно поменять, оно вводит в заблуждение.

2020-12-16 16:44 UTC, olegsklyarov commented on src/mock/filter.js
> +import dayjs from 'dayjs';
Функции нужно вынести из mock в utils, потому что они не относятся к мокам. Потом они будут применятся и к реальным данным с сервера.

2020-12-16 16:44 UTC, olegsklyarov commented on src/mock/filter.js
> +const filteredFuturetArray = eventMockData.filter((elem) => (dayjs(elem.endTime) > dayjs(today)));
Тут нужна функция, которая получает на вход массив событий и возвращает только будущие события. Название может быть `getFutureEvents()`. Не нужно явно работать с eventMockData и экспортировать переменную filteredFuturetArray.
Вместо этого в нужном месте кода нужно вызвать так:
```
const futureEvents = getFutureEvents(eventMockData);
```

2020-12-16 16:44 UTC, olegsklyarov commented on src/mock/filter.js
> +  filteredPastArray,
Экспортировать (здесь и далее) можно только функции. Нельзя экспортировать переменные.

2020-12-16 16:44 UTC, olegsklyarov commented on src/utils/form-template.js
> +  let photosContainerElement = document.querySelector(`.event__photos-container`);
Здесь и в других подобных местех используем `const` вместо `let`

2020-12-22 16:38 UTC, olegsklyarov requested changes

2020-12-22 16:38 UTC, olegsklyarov commented on src/main.js
> +const generateAddForm = () => {
Есть путаница в именованиях. Давай договоримся про однообразное именование:
renderXYZ — добавление нового HTML чего-то в DOM
generateXYZ — генерация мока
createXYXTemplate — создание строки с HTML

Поэтому уместно назвать функцию `renderAddForm`

2020-12-22 16:38 UTC, olegsklyarov commented on src/main.js
> +  render(tripEventsListElement, createAddForm(addFormTemplate()), TemplatePosition.AFTER_BEGIN);
`createAddFormTemplate` вместо `createAddForm`

2020-12-22 16:38 UTC, olegsklyarov commented on src/main.js
> +  render(tripEventsListElement, createAddForm(addFormTemplate()), TemplatePosition.AFTER_BEGIN);
`addFormPartsTemplate` вместо `addFormTemplate`, чтобы было, что тут массив кусков формы.

2020-12-22 16:38 UTC, olegsklyarov commented on src/mock/data.js
> +    MIN: 0,
Здесь и далее нужно избавиться от "магических значений", чтобы не нарушать [критерий Б31](https://up.htmlacademy.ru/ecmascript/13/criteries#b31)

2020-12-22 16:38 UTC, olegsklyarov commented on src/utils/utils.js
> +const updateLocaleTime = (time) => dayjs.updateLocale(time);
Убираем неиспользуемый код ([критерий Б18](https://up.htmlacademy.ru/ecmascript/13/criteries#b18))

2020-12-22 16:38 UTC, olegsklyarov commented on src/utils/utils.js
> +const generateTemplate = (data, callBack) => {
Функция делает render в DOM, нужно переименовать ее, чтобы не вводить в заблуждение. Например: `renderCollectionUsingCallback` или что-то подобное.

2020-12-22 16:38 UTC, olegsklyarov commented on src/view/trip-add-new-event-form/add-form-template.js
> +    placeholder: dayjs().format(`DD/MM/YYYY`)
Строку с форматом нужно вынести в константу, например в файл `const.js` на одном уровне в `main.js`. Это глобальная константа для всего проекта.

2020-12-22 16:38 UTC, olegsklyarov commented on src/view/trip-event/event-template.js
> +  generateSorterForm();
Тут явно не должна вызываться эта функция. Нужно вынести ее выше, возможно прямо в main.js

2020-12-22 16:38 UTC, olegsklyarov commented on src/view/trip-event/event-template.js
> +  for (let i = 0; i < array.length; i++) {
Логика очень похожа на `renderColectionUsingCallback` (написал выше в комментариях в этому pull request). Постарайся использовать ее.

2020-12-22 16:38 UTC, olegsklyarov commented on src/view/trip-filters/trip-filters.js
> +    isChecked: `checked`
`true`

2020-12-22 16:38 UTC, olegsklyarov commented on src/view/trip-filters/trip-filters.js
> +    isChecked: ``
`false` или вообще не указываем `isChecked`

2020-12-22 16:38 UTC, olegsklyarov commented on src/view/trip-filters/trip-filters.js
> +    isChecked: ``
И тут

2020-12-22 16:38 UTC, olegsklyarov commented on src/view/trip-sorters/sorter-template.js
> +    isChecked: `checked`,
Здесь и далее либо `true`, либо `false`

2020-12-23 12:24 UTC, merged