Module3 task1
htmlacademy-ecmascript/1474119-big-trip-13 pull request #6
Opened 2020-12-27 11:35 UTC by YuShato

2021-01-04 05:23 UTC, olegsklyarov requested changes

2021-01-04 05:23 UTC, olegsklyarov commented on src/view/trip-filters/trip-filters-template.js
> -export const createTripFilterTemplate = (filtersHtml) => {
Название экспортируемого класса должно соответствовать названию файла (модуля). Переименовываем название файла в `trip-filter.js`

2021-01-04 05:23 UTC, olegsklyarov commented on src/view/trip-add-new-event-form/add-form.js
> +  remove() {
В классе View не должно быть методов `remove` и `render`. Это будет в Presenter'е. Убираем отсюда.

2021-01-04 05:23 UTC, olegsklyarov commented on src/view/trip-add-new-event-form/types.js
> +export default class TypesWrapper {
Нужно наследоваться от `Abstract` и убрать лишние методы.

2021-01-04 05:23 UTC, olegsklyarov commented on src/view/trip-filters/trip-filters-filter-template.js
> +export default class TripFilters {
Нужно наследовать от `Abstract` и убрать лишние методы.

2021-01-05 21:23 UTC, YuShato commented on src/main.js
> +import TripInfo from "./view/page-header/info.js";
переименовала

2021-01-05 21:25 UTC, YuShato commented on src/main.js
> +import SiteMenuControls from "./view/page-header/controls.js";
переименовала

2021-01-05 21:26 UTC, YuShato commented on src/utils/render.js
> +export const render = (container, child, place) => {
готово

2021-01-05 21:28 UTC, YuShato commented on src/mock/data.js
> +  const checkedOffersList = generateTemplatesUsingClass(allOffers.filter((offer) => offer.isChecked), EventOffer);
готово

2021-01-05 21:29 UTC, YuShato commented on src/utils/filter.js
> +  if (data.length === 0 || !data) {
готово

2021-01-05 21:30 UTC, YuShato commented on src/utils/filter.js
> +    render(siteEventElement, generateEvents(data), RenderPosition.BEFORE_END);
готово

2021-01-05 21:37 UTC, YuShato commented on src/utils/filter.js
>  const siteEventElement = document.querySelector(`.trip-events`);
готово

2021-01-05 21:43 UTC, YuShato commented on src/view/trip-filters/trip-filters-template.js
> -export const createTripFilterTemplate = (filtersHtml) => {
готово

2021-01-05 21:56 UTC, YuShato commented on src/view/trip-add-new-event-form/add-form.js
> +  remove() {
готово

2021-01-05 21:57 UTC, YuShato commented on src/view/trip-add-new-event-form/types.js
> +export default class TypesWrapper {
напишу в личку

2021-01-05 22:17 UTC, YuShato commented on src/view/trip-filters/trip-filters-filter-template.js
> +export default class TripFilters {
написала в личку

2021-01-15 12:59 UTC, olegsklyarov approved these changes

2021-01-15 12:59 UTC, merged